<a href="https://colab.research.google.com/github/anvaribs/UT-COE-321K/blob/master/COE_321K_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Announcements:

---



### 1. HW#3 is due on **March 4, 2019**. 
### 2. Please follow all the guidelines for submitting your assignment. 
### 3. You should submit your assignment through **Canvas**. 
### 4. You should submit a PDF (hwX_yourEID.pdf) of your write-up and a zip file including all your source codes through Canvas. Name this zip file **hwX_yourEID.zip**.
### 5. You can resubmit your assignment before the deadline.
### 6. Only the most recent submission would be graded.

# Agenda:



 - What is google Colab? Why do we use it?
 - Intro to Python and Numpy library for numerical computation.
 - Intro to [Fenics](https://fenicsproject.org/)  using high-level Python API.
 - Example programs to solve Solid Mechanics problems.



 

# Google Colab

**You can think of Google Colab as Jupyter Notebook stored in google cloud! **

1. Everything runs on cloud. You do not have to install or build anything on your local machine. You do not have to be worried about dependencies locally. 
2. It allows you to share your work with me and other TAs, see [this](https://support.google.com/drive/answer/2494822?co=GENIE.Platform%3DDesktop&hl=en). We can run your code in a completely consistent enviroment and figure out what is going wrong.
* For interaction between colab and github see, [Using Colab with GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
3. You can also use a GPU to run your code.
4. You can extend the power of the notebook by installing new libraries using pip install.
5. Google colab integrates nicely with Github, so that you can load notebooks from Github and also save notebooks to Github.




**Note**: Environmental variables and libraries that you build does not persist accross multiple sessions.

In [1]:
print("Show available RAM memory:")
!cat /proc/meminfo | grep MemTotal

Show available RAM memory:
MemTotal:       13335276 kB


In [0]:
# print("Check CPUs info:")
# !cat /proc/cpuinfo

In [0]:
!pip install -q matplotlib-venn

import matplotlib_venn as venn

# A quick intro to Jupyter notebook

A notebook is a collection of cells. Cells can contain text, or executable code and it's outputs. Text cells use markdown syntax. See this [markdown guide](https://colab.research.google.com/notebooks/markdown_guide.ipynb) to learn more.  

You can easily call the system commands within the jupyter using a ! sign.

In [4]:
!mkdir FEM_mesh
!ls

mkdir: cannot create directory ‘FEM_mesh’: File exists
FEM_mesh  sample_data


## This is a heading

You can have lists as well.
- first item
- second item
- third item

You can easily include Math formulas using [latex](https://www.latex-project.org/). You just need to place the statement within two **\$** signs.

$$
\int_0^\pi \sin^2(2x)
$$

Or for example, you can include matrices like this:

$$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$$
 


In [5]:
# This is a code cell. 
# You can perform computations in Python in code cells and run them.

7 ** 2

49

In [6]:
# Line magics
%timeit [i+1 for i in range(1000)]

The slowest run took 6.32 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 73.4 µs per loop



This combination of text and code makes Jupyter Notebook ideal for experimentation and learning: we can see the rationale for each experiment, the code and the results in one comprehensive document.

last but not least, to include links in your Jupyter notebook, just surround the text you want to link with '[]' and place the link adjacent to the text, sorround with '()'. like [this](https://www.google.com/).


# Introduction to Python and Numpy

## Python

### Variables


Variables can come in lots of different types. Even within numerical variables, you can have integers (int), floats (float), etc. All text based variables are of type string (str). We can see what type a variable is by printing its type.

In [7]:
# int variable
x = 5
print (x)
print (type(x))

# float variable
x = 5.0
print (x)
print (type(x))

# text variable
x = "5" 
print (x)
print (type(x))

# boolean variable
x = True
print (x)
print (type(x))

5
<class 'int'>
5.0
<class 'float'>
5
<class 'str'>
True
<class 'bool'>


In [8]:
# Let's define a variable
a = 250
print(a)
print(type(a))

250
<class 'int'>


### Lists:

Lists are objects in Python that can hold a ordered sequence of numbers and text.

In [9]:
# Creating a list
list_x = [35.0, "hello", 1]
print (list_x)

# Adding to a list
list_x.append(7)
print (list_x)



# Accessing items at specific location in a list
print ("list_x[0]: ", list_x[0])
print ("list_x[1]: ", list_x[1])
print ("list_x[2]: ", list_x[2])
print ("list_x[-1]: ", list_x[-1]) # the last item
print ("list_x[-2]: ", list_x[-2]) # the second to last item


# Slicing
print ("list_x[:]: ", list_x[:])
print ("list_x[2:]: ", list_x[2:])
print ("list_x[1:3]: ", list_x[1:3])
print ("list_x[:-1]: ", list_x[:-1])


# Replacing items in a list
list_x[1] = "hi"
print (list_x)



# Combining lists
list_y = [2.4, "world"]
list_z = list_x + list_y
print (list_z)

[35.0, 'hello', 1]
[35.0, 'hello', 1, 7]
list_x[0]:  35.0
list_x[1]:  hello
list_x[2]:  1
list_x[-1]:  7
list_x[-2]:  1
list_x[:]:  [35.0, 'hello', 1, 7]
list_x[2:]:  [1, 7]
list_x[1:3]:  ['hello', 1]
list_x[:-1]:  [35.0, 'hello', 1]
[35.0, 'hi', 1, 7]
[35.0, 'hi', 1, 7, 2.4, 'world']


### Tuples

Tuples are also objects in Python that can hold data but you cannot replace their values (for this reason, tuples are called immutable, whereas lists are known as mutable).

In [10]:
# Creating a tuple
tuple_x = (3.0, "hello")
print (tuple_x)


# Adding values to a tuple
tuple_x = tuple_x + (5.6,)
print (tuple_x)


(3.0, 'hello')
(3.0, 'hello', 5.6)


In [0]:
# Trying to change a tuples value (you can't)
#tuple_x[1] = "world"

### Dictionaries


Dictionaries are Python objects that hold key-value pairs. In the example dictionary below, the keys are the "number_of_nodes" and "dof" variables. They each have a value associated with them. A dictionary cannot have two of the same keys.

In [12]:
# Creating a dictionary
input = {"number_of_nodes": 25,
        "dof": 50}
print (input)
print (input["number_of_nodes"])
print (input["dof"])



# Changing the value for a key
input["number_of_nodes"] = 60
print (input)



# Adding new key-value pairs
input["number_of_elements"] = 10
print (input)


# Length of a dictionary
print (len(input))

{'number_of_nodes': 25, 'dof': 50}
25
50
{'number_of_nodes': 60, 'dof': 50}
{'number_of_nodes': 60, 'dof': 50, 'number_of_elements': 10}
3


### Python Classes and Objects

If you are interested in OOP, learn about classes and objects [here](https://docs.python.org/3/tutorial/classes.html)

## Numpy

**Numpy is the fundamental package for scientific computing with Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also contains useful linear algebra functions, Fourier transform, and random number functions.**

If you are already a MATLAB programmer, you might find [this tutorial](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) useful. 



```
To import a library that is not in colaboratory by default, you can use !pip install.
```



In [13]:
!pip install numpy scipy matplotlib
!pip install -q matplotlib-venn
# !pip install --upgrade numpy

In [14]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
print(np.__version__)

1.16.1


In [0]:
# Get inline help
np.random?

You can also use tab-completion to explore the attributes of python objects and availble methods and functions.

In [0]:
# np.random.

In [0]:
# np.random.rand(

### Commenting on a cell
You can comment on a cell the same way that you would on Google Documents. This is going to be very handy if you want to show the TAs or your collaborators what is going wrong in your code or what they have to look at. For example, look at this peice of code:

In [0]:
x = 1
y = 4
#z = y/(1-x)

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [20]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


**Some vocabulary**
- In NumPy, each dimension is called an axis.
- The number of axes is called the rank.
- For example, the above 2x3 matrix is an array of rank 2 (it is 2-dimensional).
- The first axis has length 2, the second has length 3.
- An array's list of axis lengths is called the shape of the array.
- For example, the above matrix's shape is (2,34).
- The rank is equal to the shape's length.
- The size of an array is the total number of elements, which is the product of all axis lengths (eg. 2*3=6)

**You can create arrays in [many different ways](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation)**:

In [21]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"
  
  
# arange vs linspace
print(np.arange( 0, 2, 0.3 ))
print(np.linspace( 0, 2, 9 ))

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.75630372 0.89585368]
 [0.88989774 0.68352588]]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### Array indexing

Take a look at [this](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

#### Slicing

In [22]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


**You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:**

In [23]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Integer array indexing: 

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [24]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


#### Boolean array indexing: 
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [25]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric [datatypes](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [26]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.float)   # Force a particular datatype
print(x)
print(x.dtype)                         # Prints "int64"

int64
float64
[1. 2.]
float64


### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [27]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, **\*** is elementwise multiplication, not matrix multiplication. We instead use the **dot** function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. **dot** is available both as a function in the numpy module and as an instance method of array objects.

In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides [many](https://docs.scipy.org/doc/numpy/reference/routines.math.html) useful functions for performing computations on arrays; such as **sum, sin, cos, exp, log,  **

In [29]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


### No Copy at all

Simple assignments make no copy of array objects or of their data.



In [30]:
a = np.arange(12)
b = a            # no new object is created
print(b is a)           # a and b are two names for the same ndarray object

b.shape = 3,4    # changes the shape of a
a.shape


True


(3, 4)

Also, python passes mutable objects as references, so function calls make no copy.

In [31]:
d = a.copy()                          # a new array object with new data is created
d is a

d.base is a                           # d doesn't share anything with a

d[0,0] = 9999
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [32]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow.

Numpy broadcasting allows us to perform this computation without having a loop or actually creating multiple copies of v. Consider this version, using broadcasting:



In [33]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


It is very important that you understand how broadcasting works. So, I would suggest that you read [this](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) from the documentation.

## Linear Algebra

In [34]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)


# transpose
print('transpose: \n', a.transpose())


# inv
print('inverse: \n',np.linalg.inv(a))


# determinant
print('determinant', np.linalg.det(a))

u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
print('identity matrix: \n', u)


j = np.array([[0.0, -1.0], [1.0, 0.0]])

print('matrix product: \n', j @ j )       # matrix product



print('trace:', np.trace(u))  # trace


y = np.array([[5.], [7.]])
print('solution: ', np.linalg.solve(a, y))


[[1. 2.]
 [3. 4.]]
transpose: 
 [[1. 3.]
 [2. 4.]]
inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant -2.0000000000000004
identity matrix: 
 [[1. 0.]
 [0. 1.]]
matrix product: 
 [[-1.  0.]
 [ 0. -1.]]
trace: 2.0
solution:  [[-3.]
 [ 4.]]


In [35]:
mat = np.array([[1,2,3],[5,7,11],[21,29,31]])

eigenvalues, eigenvectors  = np.linalg.eig(mat)
print('eigenvalues: \n', eigenvalues)
print('eigenvectors: \n', eigenvectors)

mat.dot(eigenvectors) - eigenvalues * eigenvectors  # m3.v - λ*v = 0

eigenvalues: 
 [42.26600592 -0.35798416 -2.90802176]
eigenvectors: 
 [[-0.08381182 -0.76283526 -0.18913107]
 [-0.3075286   0.64133975 -0.6853186 ]
 [-0.94784057 -0.08225377  0.70325518]]


array([[ 6.66133815e-15,  1.66533454e-15, -3.10862447e-15],
       [ 7.10542736e-15,  5.16253706e-15, -5.32907052e-15],
       [ 3.55271368e-14,  4.94743135e-15, -9.76996262e-15]])

### Calculating the norm of a vector or Matrix


In [36]:
def vector_norm(vector):
    squares = [element**2 for element in vector]
    return np.sum(squares)**0.5

u = np.array([[2,5], [4,3]])
print("||", u, "|| =")
vector_norm(u)

|| [[2 5]
 [4 3]] || =


7.3484692283495345

In [37]:
np.linalg.norm(u)

7.3484692283495345